BROOT='/home/egrassi' # very nice :(
PRJ_ROOT=BROOT+'/strata'
SRC_DIR=PRJ_ROOT+'/local/src'
DATA_DIR=PRJ_ROOT+'/local/share/data'

## This dataset:
##DATA=DATA_DIR+'/bardelli_wes'
DATA=DATA_DIR
#[data]egrassi@hactarlogin$ ls *1.fastq.gz | perl -ane '/(CRC[0-9A-Z]+)/; print "\"$1\"",';
SAMPLES=["CRC0542LMX0B01001TUMD11000","CRC0542LMX0B02001TUMD02000","CRC0542LMX0B02003TUMD02000","CRC0542LMX0B03020TUMD05000","CRC0542LMX0B04006TUMD02000"]
FASTQ_SUFFIX=".xenome_graft_{pair}.fastq.gz"

PAIRS=[1,2]
# TODO need to adapt to unpaired (do they exists?) reads, will need to change the all rule in the subdirs using an input function...
CORES="4"

PATTERNED=2500 
# HiSeq4000, otherwise 100 for unpatterned


rule all_something:
    input: expand("{sample}.{{something}}", sample=SAMPLES)
    output: "all_samples_{something}"
    shell: "touch {output}"
