DEBUG="yes"
PRJ_ROOT="../.."
SRC_DIR=PRJ_ROOT+"/local/src"
BIN_DIR=PRJ_ROOT+"/local/bin"

BASE=PRJ_ROOT+"/local/share/data/pre_irino/dec2018"
MUTS="muts_gene_crc.tsv"
DICTIO_CRC=PRJ_ROOT+"/local/share/data/targeted_hr/PJ1903090-SF-Integragen-Targeted-Seq.tsv"
SANGER=BASE+"/../DTB_TargetedNGS_SangerInstitute_DriverMutations.txt"
CNV=BASE+"/all_cnv.txt"
VOLUMES=BASE+"/chemio_dec_2019.txt"
W=BASE+"/../sept2019/w3.txt"
CNV_GENES=BASE+"/all_cnv.txt"
PATHWAYS=PRJ_ROOT+"/local/share/data/targeted_hr/hr_pathways.txt"
#aplot) [pre_irino]egrassi@hactarlogin$ cat DTB_WESdata_CompleteStudy_muts.txt | cut -f 4,5 | sed 1d | sort | uniq > gs_desc
GS_DESC=BASE+"/../gs_desc"
MSI=BASE+"/MSI"


AF_CUTOFF=0.3

rule cases:
    input: DICTIO_CRC
    output: "all_cases.tsv"
    shell:
        """
           cut -f 1 {input} | sed 1d | tr "_" "\t" | cut -f 2 | bawk '{{print substr($1,0,7)}}' > {output}
        """

rule build_long:
    input: annot=PRJ_ROOT+"/local/share/data/targeted_hr/new_gatk/merged.hg38_multianno.txt", af=PRJ_ROOT+"/local/share/data/targeted_hr/new_gatk/merged.table_nomultiallele"
    output: "gene_annot_muts.tsv"
    params: tool=BIN_DIR+"/select_annovar_table"
    shell:
        """
            {params.tool} {input.annot} {input.af} > {output}
        """
        

rule mut_gene:
    output: "muts_nonsyngene_crc.tsv"
    input: "gene_annot_muts.tsv"
    shell: 
        """
            bawk '$6!="synonymous SNV" {{print $1,$4}}' < {input} > {output}
        """


rule mut_cosmic:
    output: "muts_cosmicgene_crc.tsv"
    input: "gene_annot_muts.tsv"
    shell: 
        """
            bawk '$6!="synonymous SNV" && $7 != "." {{print $1,$4}}' < {input} > {output}
        """

### filter using integragen PON
rule PON:
    output: "pon_filter"
    shell:
        """
            zcat ../../local/share/data/targeted_hr/Results/Results_DNA/02_Variants/Oncology/PON*.vcf.gz | grep -v "^#" | cut -f 1,2,4,5,7 | grep panel_of_normal | bawk '{{print $1":"$2":"$3":"$4}}' | sort | uniq > {output} 
        """

rule mut_PON_gene:
    output: "muts_nonsynPONgene_crc.tsv"
    input: muts="gene_annot_muts.tsv", pon="pon_filter"
    shell: 
        """
            bawk '$6!="synonymous SNV" {{print $1,$4,$3}}' < {input.muts} | filter_1col 3 -v {input.pon} | cut -f 1,2 > {output}
        """

rule mut_PON_gene_AF:
    output: "muts_{AF}-nonsynPONgene_crc.tsv"
    input: muts="gene_annot_muts.tsv", pon="pon_filter"
    shell: 
        """
            bawk '$6!="synonymous SNV" &&  $2 > {wildcards.AF} {{print $1,$4,$3}}' < {input.muts} | filter_1col 3 -v {input.pon} | cut -f 1,2 > {output}
        """
###
rule sanger_all:
    input: mut=SANGER
    output: "muts_sanger.txt"
    shell:
        """
            grep LMX {input.mut} |  perl -ane 'my $c=substr($F[0],0,7); print "$c\\t$F[7]\\n"' > {output}
        """

rule mergione:
    input: hr="muts_nonsynPONgene.txt", sanger="muts_sanger.txt"
    output: "muts_ATRmergegene_crc.tsv"
    shell: 
        """
        grep -w ATR {input.hr} > {output}.tmp
        grep -w ATR {input.sanger} >> {output}.tmp
        sort {output}.tmp | uniq > {output}
        """

# muts_ATRmergegene_crc.tsv manually edited, removing CRC0123 who we decided to filter out

rule allcasesmergione:
    input: "all_cases.tsv", "../exomes_other_dec18/muts_sanger.txt"
    output: "all_cases_merged.tsv"
    shell: "cut -f 1 {input} | sort | uniq > {output}"

rule modello_mergione:
    input: volumes=W, pivot="muts_ATRmergegene_pivot.txt", msi=MSI, all_samples="all_cases_merged.tsv"
    output: linear="{w}_linear_model.tsv", logistic="{w}_logistic_model.tsv", linearxls="{w}_linear_model.xls"
    params: debug=DEBUG, pdx="pdx", cutoff=3, plotdir="ATR_plots"
    script: SRC_DIR+"/models_vol_pivot_listsamples.R"
